import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const staticDir = path.resolve(__dirname, ".vercel/output/static");
const port = process.env.PORT || 10000;

// Import the Nitro server handler generated by the build
let nitroHandler;
try {
  const mod = await import("./.vercel/output/functions/__server.func/index.mjs");
  nitroHandler = mod.default || mod;
} catch (e) {
  console.warn("Could not load nitro server function, falling back to static", e);
}

const mimeTypes = {
  ".html": "text/html",
  ".js": "text/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".wasm": "application/wasm",
  ".glb": "model/gltf-binary",
  ".gltf": "model/gltf+json",
};

const server = http.createServer((req, res) => {
  const reqPath = decodeURI(req.url.split("?")[0]);
  const filePath = path.join(staticDir, reqPath === "/" ? "index.html" : reqPath);

  // If a physical static asset exists (JS chunks, CSS, images), serve it directly
  fs.stat(filePath, (err, stats) => {
    if (!err && stats.isFile()) {
      const ext = path.extname(filePath).toLowerCase();
      res.writeHead(200, { "Content-Type": mimeTypes[ext] || "application/octet-stream" });
      fs.createReadStream(filePath).pipe(res);
    } else if (typeof nitroHandler === "function") {
      // Delegate page requests and SSR routing to Nitro
      nitroHandler(req, res);
    } else {
      res.writeHead(404, { "Content-Type": "text/plain" });
      res.end("Not Found");
    }
  });
});

server.listen(port, "0.0.0.0", () => {
  console.log(`Render Web Service listening on 0.0.0.0:${port}`);
});
